---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.c930.net
  resources:
  - sleeps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.c930.net
  resources:
  - sleeps/finalizers
  verbs:
  - update
- apiGroups:
  - demo.c930.net
  resources:
  - sleeps/status
  verbs:
  - get
  - patch
  - update
