# permissions for end users to edit sleeps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sleep-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sleep-operator
    app.kubernetes.io/part-of: sleep-operator
    app.kubernetes.io/managed-by: kustomize
  name: sleep-editor-role
rules:
- apiGroups:
  - demo.c930.net
  resources:
  - sleeps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.c930.net
  resources:
  - sleeps/status
  verbs:
  - get
